config/routes.rb
Rails.application.routes.draw do

  resources :billings do
    member do
      get :product_details
    end
  end
  resources :customers do
    member do
      post :send_email
    end
  end
  resources :products
  resources :denominations

  root 'billings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord

  ####################   Validations   #############################

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_format_of :email, with: EMAIL_REGEX
  validates :amount, numericality: { greater_than: 0, only_integer: true }
  validate :paid_amount


  def paid_amount
    if self.product_details.size < 1
      errors.add(:product,'list is less than 1')
    else
      self.amount=0 if self.amount.nil?
      if self.amount >= self.total_bill
        @amount = self.amount - self.total_bill
        @balance = {}
        @sum     = 0
        Denomination.all.order(rupees: :desc).each do |denomination|
          if @amount >= denomination.rupees
            @count = @amount/denomination.rupees

            if denomination.count >=  @count
              @balance[denomination.rupees] =  @count.to_i
              @amount %= denomination.rupees
              @sum += (denomination.rupees*@count.to_i)
            else
              @balance[denomination.rupees] = denomination.count
              @amount -= (denomination.rupees * denomination.count)
              @sum += (denomination.rupees*denomination.count)
            end
          end
        end

        if @sum==self.amount-self.total_bill
          self.balance = @balance
          @balance.each do |rupees,count|
            @denomination = Denomination.find_by_rupees(rupees)
            @denomination.update(count: @denomination.count-count)
          end
        else
          errors.add(:balance,' not enough in shop')
        end
      else
        errors.add(:total_bill, "- Paid amount is less than purchased amount")
      end
    end
  end



  ####################  Association    ############################

  has_many :product_details, dependent: :destroy
  has_many :products, through: :product_details
  accepts_nested_attributes_for :product_details

end

app/models/denomination.rb
class Denomination < ApplicationRecord

  ############  Validation  ################

  validates :rupees, uniqueness: true, numericality: { greater_than:  0 }
  validates_numericality_of :count, greater_than_or_equal_to: 0
end

app/models/product.rb
class Product < ApplicationRecord

  ##########  Validation  ###############

  validates :name, presence: true, uniqueness: true
  validates_numericality_of :unit_price, greater_than: 0
  validates_numericality_of :tax_percentage, greater_than: 0
  validate :whether_it_has_child

  def whether_it_has_child
    if self.product_details.size > 0
      errors.add(:product, " used in existing customers bill, so can't update")
    end
  end

  ###########  Association ##############

  has_many :product_details, :dependent => :restrict_with_error
  has_many :billings, through:  :product_details
end

app/models/product_detail.rb
class ProductDetail < ApplicationRecord

  #################  Validation  #####################


  validates :quantity, presence: true

  #################   Association  ###################

  belongs_to :billing
  belongs_to :product

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController

  def index
    if Product.count==0
      redirect_to products_path, alert: 'You have 0 products in billing. So please create one product for billing!!!'
    end
    @new_one = Billing.new
    @product = Product.first
    @products = Product.all
  end


  def product_details
    @product = Product.find(params[:id])
    respond_to do |format|
      format.json { render json: {id: @product.id,unit_price: @product.unit_price,tax: @product.tax_percentage} }
    end

  end

  def create
    @product = Product.first
    @new_one = Billing.new(get_billing)
    respond_to do |format|
      if @new_one.save
        PurchaseMailer.show_details(@new_one).deliver
        format.js { redirect_to customer_path(@new_one), notice: "Customer details saved successfully!!!" }
        format.html
      else
        format.js
        format.html
      end
    end
  end

  private
    def get_billing
      params.require(:billing).permit(:email, :amount, :without_tax, :tax_price, :total_bill, product_details_attributes: [:product_id,:name, :quantity, :unit_price,:purchased_price, :tax_percentage_for_item, :tax_payable_for_item, :total_price_of_item])
    end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  include Pagy::Backend

  before_action :get_billing_by_id, except: :index

  def index
    @pagy, @customers = params[:email].present? ? pagy(Billing.where(email: params[:email]).order(created_at: 'DESC'), items: 10) : pagy(Billing.all.order(created_at: 'DESC'), items: 10)
  end

  def show
    @product_details  = @billing.product_details.includes(:product)
  end

  def send_email
    PurchaseMailer.show_details(@billing).deliver

    redirect_to customer_path(@billing), notice: "Email sent successfully!!!"
  end

  private
    def get_billing_by_id
      @billing = Billing.find(params[:id])
    end
end

app/controllers/denominations_controller.rb
class DenominationsController < ApplicationController

  before_action :get_denomination_id, only: [:edit, :update, :destroy]
  after_action :clear_flash, only: [:create, :update, :destroy]

  def index
    @denominations = Denomination.all.order(rupees: :desc)
  end

  def new
    @denomination = Denomination.new
    respond_to do |format|
      format.js
      format.html
    end
  end

  def create
    @denomination = Denomination.new(get_denomination)
    flash[:notice] = "Denomination created successfully!!!"
    respond_to do |format|
      if @denomination.save
        format.js
        format.html
      else
        format.js
        format.html
      end
    end

  end

  def edit
    respond_to do |format|
      format.js
      format.html
    end
  end

  def update
    flash[:notice] = "Denomination updated successfully!!!"
    respond_to do |format|
      if @denomination.update(get_denomination)
        format.js
        format.html
      else
        format.js
        format.html
      end
    end
  end

  def destroy
    @denomination.destroy
    flash[:notice] = "Denomination deleted successfully!!!"
    respond_to do |format|
      format.js
      format.html
    end
  end

  private
    def get_denomination
      params.require(:denomination).permit(:rupees,:count)
    end

    def get_denomination_id
      @denomination = Denomination.find(params[:id])
    end

    def clear_flash
      flash.discard
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :find_product, only: [:edit, :update, :destroy]
  after_action :clear_flash, only: [:create, :update, :destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    respond_to do |format|
      format.js
      format.html
    end
  end

  def create
    @product = Product.new(get_products)
    flash[:notice] = "Product created successfully!!!"
    respond_to do |format|
      if @product.save
        format.html
        format.js
      else
        format.html
        format.js
      end
    end
  end

  def edit
    respond_to do |format|
      format.js
      format.html
    end
  end

  def update
    flash[:notice] = "Product updated successfully!!!"
    respond_to do |format|
      if @product.update(get_products)
        format.js
        format.html
      else
        format.js
        format.html
      end
    end
  end

  def destroy
    @product.destroy
    if @product.errors.any?
      flash[:notice] = 'Cannot delete the product, since it is added in some bills'
    else
      flash[:notice] = 'Product deleted successfully!!!'
    end
    respond_to do |format|
      format.js
      format.html
    end
  end
  private
    def get_products
      params.require(:product).permit(:name, :unit_price, :tax_percentage)
    end

    def find_product
      @product = Product.find(params[:id])
    end

    def clear_flash
      flash.discard
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/denominations_helper.rb
module DenominationsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/billings/_errors.html.erb
<div id="for_errors">
  <h1>Please provide valid informations</h1>
  <ul>
    <% new_one.errors.full_messages.each do |message| %>
      <li><%= message %><br/></li>
    <% end %>
  </ul>
</div>

app/views/billings/create.js.erb
<% if @new_one.errors.any? %>
  $('#error_values').html('<%= j render 'errors', new_one: @new_one %>');
<% end %>

app/views/customers/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">

  <a class="navbar-brand" href="/denominations">Denominations</a>
  <a class="navbar-brand" href="/billings">New Bill</a>
  <a class="navbar-brand" href="/products">Products</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="pull-right">
    <form class="form-inline ml-auto" action="/customers" method="get">
      <div class="md-form my-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="email" autocomplete="off">
      </div>
      <button class="btn btn-light" type="submit">Search</button>
      <i class="fas fa-search text-white ml-3" aria-hidden="true"></i>
    </form>
    </div>
  </div>

</nav>
<h1>DETAILS OF A CUSTOMERS</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Paid amount</th>
      <th>Purchased Date</th>
      <th>Purchased Time</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.email, customer_path(customer) %><br/></td>
        <td><%= customer.amount %></td>
        <td><%= customer.created_at.to_date %></td>
        <td><%= customer.created_at.strftime("%I:%M %p") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="form-inline">
  <%= render template: "shared/paginator", locals: { pagy: @pagy }%>
</div>

app/views/customers/show.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">

  <a class="navbar-brand" href="/customers">Bill List</a>
  <a class="navbar-brand" href="/denominations">Denominations</a>
  <a class="navbar-brand" href="/billings">New Bill</a>
  <a class="navbar-brand" href="/products">Products</a>

</nav>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>
<div class="row">
  <div class="col-md-1" style="background: powderblue">

  </div>
  <div class="col-md-10">
      <h1>Billing System</h1>

    <br/>
    <p><b>Customer Email</b></p>
    <p><%= @billing.email %></p>
    <br/>

    <h1>Bill Section<%= link_to 'Send email', send_email_customer_path, method: :post, class: 'btn btn-success', style: 'float: right' %></h1>
    <table class="table table-striped">
      <thead align="center">
      <tr>
        <th>Product name</th>
        <th>Unit Price</th>
        <th>Quantity</th>
        <th>Purchased Price</th>
        <th>Tax % for item</th>
        <th>Tax payable for item</th>
        <th>Total price of the item</th>
      </tr>
      </thead>
      <tbody align="center">
      <% @product_details.each do |product_detail| %>
        <tr>
          <td><%= product_detail.product.name %></td>
          <td><%= '%.2f' % product_detail.product.unit_price %></td>
          <td><%= product_detail.quantity %></td>
          <td><%= '%.2f' % product_detail.purchased_price %></td>
          <td><%= product_detail.product.tax_percentage %></td>
          <td><%= '%.2f' % product_detail.tax_payable_for_item %></td>
          <td><%= '%.2f' % product_detail.total_price_of_item %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br/>
    <h1>Balance Denominations</h1>
    <% @billing.balance.each do |rupees,count| %>
      <div class="form-group row">
        <div class="col-md-1">
          <%= rupees %>
        </div>
        <div class="col-md-2">
          <%= count %>
        </div>
      </div>

    <% end %>

  </div>
  <div class="col-md-1" style="background: powderblue">

  </div>
</div>

  <div class="row">
    <div class="col-md-1" style="background: powderblue">

    </div>
    <div class="col-md-9" align="right" style="background: #DADADA">
      <br/>
      <p><b>Total price without tax:</b></p>
      <p><b>Total tax payable:</b></p>
      <p><b>Net prize of the purchased item:</b></p>
      <p><b>Rounded down value of the purchased items net price:</b></p>
      <p><b>Balance payable to the customer:</b></p>
    </div>
    <div class="col-md-1" style="background: #DADADA">
      <br/>

      <p align="right"><%= '%.2f' % @billing.without_tax %></p>
      <p align="right"><%= '%.2f' % @billing.tax_price %></p>
      <p align="right"><%= '%.2f' % (@billing.without_tax + @billing.tax_price) %></p>
      <p align="right"><%= '%.2f' % (@billing.without_tax + @billing.tax_price).to_i %></p>
      <p align="right"><%= '%.2f' % (@billing.amount - (@billing.without_tax + @billing.tax_price).to_i ) %></p>

    </div>
    <div class="col-md-1" style="background: powderblue">

    </div>
  </div>

app/views/denominations/_denomination_row.html.erb
<td><%= denomination.rupees %></td>
<td><%= denomination.count %></td>
<td><%= link_to 'Update', edit_denomination_path(denomination), class: 'btn btn-primary', remote: true %></td>
<td><%= link_to 'Delete', denomination_path(denomination), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', id: denomination.id, remote: true %></td>

app/views/denominations/_errors.html.erb
<div id="errors">
  <h1><%= denomination.errors.count %> errors occured</h1>
  <ul>
    <% denomination.errors.full_messages.each do |message| %>
      <li>
        <%= message %><br/>
      </li>
    <% end %>
  </ul>
</div>

app/views/denominations/_form.html.erb
<%= form_for denomination, remote: true do |denominations| %>

  <div id="error_division"></div>


  <div class="form-group row">
    <label for="rupees" class="col-md-2">Rupees</label>
    <div class="col-md-8">
      <%= denominations.text_field :rupees, autocomplete: 'off', class: 'form-control col-md-8' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="count" class="col-md-2">Count</label>
    <div class="col-md-8">
      <%= denominations.text_field :count, autocomplete: 'off', class: 'form-control col-md-8' %>
    </div>
  </div>

  <%= denominations.submit 'Submit', class: 'bt btn-success' %>
<% end %>
<br/>

app/views/denominations/create.js.erb
<% if @denomination.errors.any? %>
  $('#error_division').html('<%= j render 'errors', denomination: @denomination %>')
<% else %>
  $('#denominations').modal('hide');
  $('#denomination_table').append('<tr id="denomination_<%= @denomination.id %>">\n'+'<%= j render 'denominations/denomination_row', denomination: @denomination %>\n'+'</tr>');
  $('#flash_message').html('<div class="alert alert-success" id="message_shower"><%= flash[:notice] %></div>');
  setTimeout(remove_flash_message,3000);

  function remove_flash_message(){
      $('#message_shower').remove();
  }
<% end %>

app/views/denominations/destroy.js.erb
var denomination = document.getElementById("<%= @denomination.id %>");
denomination.parentNode.parentNode.remove();
$('#flash_message').html('<div class="alert alert-danger" id="message_shower"><%= flash[:notice] %></div>');
setTimeout(remove_flash_message,3000);

function remove_flash_message(){
    $('#message_shower').remove();
}

app/views/denominations/edit.html.erb
<h1>Update Denomination</h1><br/>
<%= render 'form', denomination: @denomination %>

app/views/denominations/edit.js.erb
$('#denominations').modal();
$('#title').html('Update denomination');
$('#form').html('<%= j render 'form', denomination: @denomination %>')

app/views/denominations/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">


  <a class="navbar-brand" href="/customers">Bill List</a>
  <a class="navbar-brand" href="/billings">New Bill</a>
  <a class="navbar-brand" href="/products">Products</a>

</nav>
<div id="flash_message"></div>

<h1>In denominations</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Rupees</th>
      <th>Count</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody id="denomination_table">
    <% @denominations.each do |denomination| %>
      <tr id="denomination_<%= denomination.id %>">
        <%= render 'denominations/denomination_row', denomination: denomination %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Denomination', new_denomination_path, class: 'btn btn-success', remote: true %>
<div class="modal fade" id="denominations" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="title"></h1>
      </div>
      <div class="modal-body">
        <div id="form"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/denominations/new.html.erb
<h1>New Denomination</h1><br/>
<%= render 'form', denomination: @denomination %>

app/views/denominations/new.js.erb
$('#denominations').modal();
$('#title').html('New denomination');
$('#form').html('<%= j render 'form', denomination: @denomination %>')

app/views/denominations/update.js.erb
<% if @denomination.errors.any? %>
  $('#error_division').html('<%= j render 'errors', denomination: @denomination %>');
<% else %>
  $('#denominations').modal('hide');
  $('#denomination_<%= @denomination.id %>').html('<%= j render 'denominations/denomination_row', denomination: @denomination %>');
  $('#flash_message').html('<div class="alert alert-info" id="message_shower"><%= flash[:notice] %></div>');
  setTimeout(remove_flash_message,3000);

  function remove_flash_message(){
      $('#message_shower').remove();
  }
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>BillingSystem</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_errors.html.erb
<div id="errors">
  <h1><%= products.errors.count %> errors occured</h1>
  <ul>
    <% products.errors.full_messages.each do |message| %>
      <li>
        <%= message %><br/>
      </li>
    <% end %>
  </ul>
</div>

app/views/products/_form.html.erb
<%= form_for products, remote: true do |product| %>


    <div id="error_division">
    </div>


    <div class="form-group row">
      <label for="name" class="col-md-4">Product Name</label>
      <div class="col-md-8">
        <%= product.text_field :name, class: 'form-control col-md-8', placeholder: 'Enter unique name', autocomplete: 'off' %>
      </div>
    </div>

    <div class="form-group row">
      <label for="unit_price" class="col-md-4">Unit Price</label>
      <div class="col-md-8">
        <%= product.text_field :unit_price, class: 'form-control col-md-8', placeholder: 'Enter Unit price', autocomplete: 'off' %>
      </div>
    </div>

    <div class="form-group row">
      <label for="tax_percentage" class="col-md-4">Tax percentage</label>
      <div class="col-md-8">
        <%= product.text_field :tax_percentage, class: 'form-control col-md-8', placeholder: 'Enter tax% for product', autocomplete: 'off' %>
      </div>
    </div>

  <br/>
  <%= product.submit 'Submit', class: 'btn btn-success' %>
<% end %>

app/views/products/_product_row.html.erb
<td><%= product.name %></td>
<td><%= product.unit_price %></td>
<td><%= product.tax_percentage %></td>
<td><%= link_to 'Update', edit_product_path(product), class: 'btn btn-primary', remote: true %></td>
<td><%= link_to 'Delete', product_path(product) ,method: :delete, data: { confirm: 'Are you sure to delete the product?'}, class: 'btn btn-danger', id: product.id, remote: true %></td>

app/views/products/create.js.erb
<% if @product.errors.any? %>
  $('#error_division').html('<%= j render 'errors',products: @product %>');
<% else %>
  $('#products').modal('hide');
  $('#product_table').append('<tr id="product_<%= @product.id %>">\n'+'<%= j render 'products/product_row', product: @product %>\n'+'</tr>');
  $('#flash_message').html('<div class="alert alert-success" id="message_shower"><%= flash[:notice] %></div>');
  setTimeout(remove_flash_message,3000);

  function remove_flash_message(){
      $('#message_shower').remove();
  }
<% end %>

app/views/products/destroy.js.erb
var product = document.getElementById("<%= @product.id %>");
<% unless @product.errors.any? %>
  product.parentNode.parentNode.remove();
<% end %>
$('#flash_message').html('<div class="alert alert-danger" id="message_shower"><%= flash[:notice] %></div>');
setTimeout(remove_flash_message,3000);

function remove_flash_message(){
    $('#message_shower').remove();
}

app/views/products/edit.html.erb
<%= render 'form', products: update_product %>

app/views/products/edit.js.erb
$('#products').modal();
$('#title').html('Update product');
$('#form').html('<%= j render 'form', products: @product %>')

app/views/products/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">


  <a class="navbar-brand" href="/customers">Bill List</a>
  <a class="navbar-brand" href="/denominations">Denominations</a>
  <a class="navbar-brand" href="/billings">New Bill</a>

</nav>
<div id="flash_message"></div>
<% if flash[:alert] %>
  <div class="alert alert-warning">
    <%= flash[:alert] %>
  </div>
<% end %>
<h1>Available products in the shop</h1>
<table class="table table-striped">
  <thead align="center">
    <tr>
      <th>Product Name</th>
      <th>Unit price</th>
      <th>Tax percentage</th>
      <th>Edit</th>
      <th>Remove</th>
    </tr>
  </thead>
  <tbody align="center" id="product_table">
    <% @products.each do |product| %>
      <tr id="product_<%= product.id %>">
        <%= render 'products/product_row', product: product %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add new product', new_product_path, class: 'btn btn-success',  remote: true, 'data-toggle' =>  "modal", 'data-target' => '#new_product' %>
<div class="modal fade" id="products" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="title"></h1>
      </div>
      <div class="modal-body">
        <div id="form"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<%= render 'form', products: @product %>

app/views/products/new.js.erb
$("#products").modal();
$('#title').html('New product');
$('#form').html('<%= j render 'form', products: @product %>')

app/views/products/update.js.erb
<% if @product.errors.any? %>
  $('#error_division').html('<%= j render 'errors', products: @product %>');
<% else %>

  $('#products').modal('hide');
  $('#product_<%= @product.id %>').html('<%= j render 'products/product_row', product: @product %>');
  $('#flash_message').html('<div class="alert alert-info" id="message_shower"><%= flash[:notice] %></div>');
  setTimeout(remove_flash_message,3000);

  function remove_flash_message(){
      $('#message_shower').remove();
  }
<% end %>

app/views/shared/paginator.html.erb
<% link = pagy_link_proc(pagy, 'class="page-link"') %>
<nav aria-label="pager"  class="pagy-bootstrap-nav" role="navigation">
  <ul class="pagination">
    <% if pagy.prev %>
      <li class="page-item prev"><%== link.call(pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"') %></li>
    <% else %>
      <li class="page-item prev disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.prev') %></a></li>
    <% end -%>
    <% pagy.series.each do |item| %>
      <%# series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36] %>
      <% if item.is_a?(Integer) %>
        <li class="page-item"><%== link.call(item) %></li>
      <% elsif item.is_a?(String) %>
        <li class="page-item active"><%== link.call(item) %></li>
      <% elsif item == :gap %>
        <li class="page-item disabled gap"><a href="#" class="page-link"><%== '<i class="fas fa-ellipsis-h"></i>' %></a></li>
      <% end %>
    <% end %>
    <% if pagy.next %>
      <li class="page-item next"><%== link.call(pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next"') %></li>
    <% else %>
      <li class="page-item next disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.next') %></a></li>
    <% end %>
  </ul>
</nav>